version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env

    ports:
      - 5432:5432

  app:
    container_name: full_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    # depends_on:
    #   - db
    ports:
      - "8000:8000"
